version: "3.7"
services:
  app:
    build:
      context: .
    image: ${APP_NAME}
    container_name: ${APP_NAME}-app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: bash -c "npm install && npm run start:dev"
    networks:
      - appnetwork
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    logging:
      driver: none
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    networks:
      - appnetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-${APP_NAME}
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - ${PMA_PORT}:80
    networks:
      - appnetwork

networks:
  appnetwork:
    name: ${APP_NAME}
    driver: bridge

volumes:
  mysql-data: